handle large lists in metadata panel
fairspace/workspace pull request #1409
Opened 2023-04-19 14:10 UTC by frankyhollywood

- windowed rendering,
- prevent slow item lookup
- show number of items in list

2023-04-19 14:13 UTC, frankyhollywood commented on projects/mercury/src/metadata/common/jsonLdConverter.js
Main change is some restructuring, made it easier to find the performance bottleneck. Turned out to be the 'generateValueEntry' method. 

I do like to keep it like this, because the conditional is now more clear:

if (predicateUri.startsWith('_')) {
            processFirstPredicateId(predicateUri);
        } else {
            processValues(predicateUri);

2023-04-25 13:12 UTC, ewelinagr commented on projects/mercury/src/metadata/common/jsonLdConverter.js
It looks like something doesn't work correctly now, because it displays id instead of label for some properties, see below:
![Screenshot from 2023-04-25 15-09-28](https://user-images.githubusercontent.com/20908736/234287198-20b85556-0d55-4b7c-abf7-2948c52457fb.png)

2023-04-25 13:19 UTC, ewelinagr commented on projects/mercury/src/metadata/common/LinkedDataProperty.js
> +                                {label} {values.length > 1 && "(" + values.length + ")"}
nice idea and looks good!

2023-04-25 13:32 UTC, ewelinajozwik commented on projects/mercury/src/metadata/common/jsonLdConverter.js
> +    label: entry['@id'] && getLabel(entry)
it looks like this is the part where it doesn't work now

2023-04-25 13:42 UTC, ewelinagr requested changes
The list looks really good, but there is an issue with the labels and there are some failing tests.

2023-05-15 13:28 UTC, FrankyHollywood commented on projects/mercury/src/metadata/common/LinkedDataProperty.js
> +                                {label} {values.length > 1 && "(" + values.length + ")"}
thx :)

2023-05-17 07:05 UTC, ewelinagr approved these changes
I tested and it works fine now!

2023-05-17 12:48 UTC, merged